[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "s3-precipitation-rodeo"
version = "0.1.0"
description = "Reproducible precipitation product analysis"
requires-python = ">=3.9"
dependencies = [
  "xarray",
  "pandas",
  "numpy",
  "pyyaml",
  "pint",
  "geopandas",
  "shapely",
  "netCDF4",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["rodeo"]
